### ISSUE TITLE
F1.3: The application should allow users to filter the list of questions.

### ISSUE THREAD

**Issue by chiewyx** [CS3219-AY2425S1/cs3219-ay2425s1-project-g27#6]
1.3.1. Application should allow users to filter based on question difficulty.
1.3.2. Application should allow users to filter based on topic.

**Comment by JunHao247** [comment]
@chiewyx In PR#10, able to sort by difficulty and topic. However, for newest, it is not going back to the default timestamped. Do we leave it for now?

**Comment by JunHao247** [comment]
> > @chiewyx In PR#10, able to sort by difficulty and topic.
> 
> i think I didn't do this eh in PR#10

@chiewyx Oh right, I got the wrong PR, I meant the sorting done by @Aloynz in PR#11, but just clarifying are we leaving this issue open for the list of questions page?

**Comment by chiewyx** [comment]
@JunHao247 yep i think we should leave this open, oh and should the sorting and filtering be done at client side or server side for list of questions

**Comment by chiewyx** [comment]
> @JunHao247 yep i think we should leave this open, oh and should the sorting and filtering be done at client side or server side for list of questions

@Aloynz @CedricChia123 @gmengqi any thoughts on where yall wna do the sorting and filtering for list of questions?

**Comment by JunHao247** [comment]
@chiewyx my bad missed out on the reply, I think since the list of questions will grow, SSR might be better, so instead of Dashboard sorting, it will be in controller?
